Spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sakshi
    password: sakshi
  jpa:
    hibernate:
      ddl-auto: update
    
plan-api:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Saving Failed
    planUpdateSucc: Plan Update Successfultty
    planUpdateFail: Plan Update Failed
    planDeleteSucc: Plan Deleted Successfully
    planDeleteFail: Plan Delete Failed
    planStatusChange: Plan Status Changed Successfully
    planStatusChangeFail: Plan Status Change Failed
    